from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig

# Load the dataset using Hugging Face's datasets library
huggingface_dataset_name = "knkarthick/dialogsum"
dataset = load_dataset(huggingface_dataset_name)

# Load the pre-trained model and tokenizer
model_name = 'google/flan-t5-base'
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Function to summarize the input text
def summarize_text(input_text):
    # Create a prompt for the model to summarize
    prompt = f"Summarize the following conversation:\n\n{input_text}\n\nSummary:"
    
    # Tokenize the input text
    inputs = tokenizer(prompt, return_tensors='pt')
    
    # Generate the summary
    summary = tokenizer.decode(
        model.generate(
            inputs["input_ids"], 
            max_new_tokens=50
        )[0], skip_special_tokens=True
    )
    
    return summary

# Function to summarize an article
def summarizer_text(input_text):
    # Tokenize the input text
    inputs = tokenizer(input_text, return_tensors='pt')
    
    # Generate the summary
    summary = tokenizer.decode(
        model.generate(
            inputs["input_ids"], 
            max_new_tokens=50
        )[0], skip_special_tokens=True
    )
    
    return summary

# Now, replace the part that asks for input with a predefined article text:
def display_summary():
    # Predefined URL for the article (replace with the desired URL)
    url = 'https://www.npr.org/2025/01/18/nx-s1-5266146/tiktok-offline-supreme-court-ban'
    article_text = scrape_article(url)  # Scrape article
    summary = summarizer_text(article_text)  # Summarize article

    # Print the original article text and summary
    print("Original Article:\n")
    print(article_text)  # Print the original article text

    print("\nSummary:\n")
    print(summary)  # Print the summary generated by the Python function

if __name__ == "__main__":
    display_summary()  # Call the function to print out the results
