from scraper import scrape_article  # Import scrape_article from scraper.py
from ml import summarizer_text  # Import summarizer_text from ml.py

def display_summary():
    # Predefined URL for the article
    url = 'https://www.npr.org/2025/01/18/nx-s1-5266146/tiktok-offline-supreme-court-ban'  # Example URL
    article_text = scrape_article(url)  # Scrape article
    summary = summarizer_text(article_text)  # Summarize article

    # Print the original article text and summary
    print("Original Article:\n")
    print(article_text)  # Print the original article text

    print("\nSummary:\n")
    print(summary)  # Print the summary generated by the Python function

if __name__ == "__main__":
    display_summary()  # Call the function to print out the results
